api_server:
  launch_sllm_service: true
  path_save: /home/wenyiw/aurora_rayserver/data_local/results
  requests_number: -1
  sorted_policy: FCFS_batch
benchmark:
  output_result_dir: /home/wenyiw/aurora_rayserver/data_local/results/sparse
  output_trace_path: /home/wenyiw/aurora_rayserver/data_local/output_traces/sparse_300s_300x.jsonl
disable_continuous_batching: true
gpu_topology:
  num_gpus_per_node: 4
  num_nodes: 1
local_storage_path: /local/scratch/models
models:
- meta-llama/Meta-Llama-3-8B-Instruct:
    mode: chat
    num_replicas: 4
    size: 8
    tensor_parallel_size: 1
port: 8000
router_replicas: 16
seed: 42
sllm_mem_pool_size: 128GB
sllm_store_timeout: 900
storage_path: /home/wenyiw/agpt/mpi-llm/models
