"""Engine-process self-attestation (plan WP3.13/WP4, audit IMP-B04, EN-01).

The vLLM ``EngineCore`` runs in a spawned subprocess that ExaServe does not
import into. Until now it was attested by its owning replica — an honest but
weak evidence class: the owner can prove the executable and the prepared
environment, never that a patch took effect *inside* the engine.

This module closes that gap without giving the engine a Ray connection. The
generated ``sitecustomize`` shim (EN-01) already runs at engine-interpreter
startup; it now also writes a receipt describing what THIS process actually
received, and the owning replica forwards those receipts to the control plane.

The distinction that keeps it honest: the shim reports whether the patch set
was *delivered* to this process at all.

- PP deployments install the patch import, so the shim proves each required
  patch with the same in-process sentinels the replica uses.
- Non-PP deployments deliberately do not deliver the vLLM/PP patches to the
  engine (they are not needed there), so every required patch is recorded as
  ``not_applicable`` — never as applied, and never as a failure.

Version strings are passed in from the replica so the shim does not import Ray
inside an engine process just to read ``__version__``.
"""

from __future__ import annotations

import glob
import json
import os
import time
from typing import Iterable, Optional

RECEIPT_DIR_ENV = "EXASERVE_ENGINE_RECEIPT_DIR"
IMPORT_PATCHES_ENV = "EXASERVE_ENGINE_SHIM_PATCHES"

# Written verbatim as sitecustomize.py on the engine's PYTHONPATH. It must stay
# import-light and must never raise: an engine that cannot write a receipt still
# has to start (readiness then blocks on the missing receipt, which is the
# correct outcome, rather than the engine failing to boot).
_SHIM_SOURCE = '''\
"""Generated by exaserve.compat.engine_shim (EN-01). Do not edit."""
import os

_want_patches = os.environ.get("EXASERVE_ENGINE_SHIM_PATCHES") == "1"
_imported = False
if _want_patches:
    try:
        import exaserve._sitecustomize  # noqa: F401
        _imported = True
    except Exception:
        _imported = False

try:
    from exaserve.compat.engine_shim import write_engine_receipt

    write_engine_receipt(patches_imported=_imported)
except Exception:
    pass
'''


def shim_source() -> str:
    return _SHIM_SOURCE


def install(shim_dir: str, receipt_dir: str, *, import_patches: bool,
            deployment_id: str, generation: int, vendor: str,
            versions: Optional[dict] = None) -> bool:
    """Write the shim and point the child interpreter at it. Never raises."""
    try:
        os.makedirs(shim_dir, exist_ok=True)
        os.makedirs(receipt_dir, exist_ok=True)
        shim_path = os.path.join(shim_dir, "sitecustomize.py")
        current = ""
        if os.path.exists(shim_path):
            with open(shim_path, encoding="utf-8") as fh:
                current = fh.read()
        if current != _SHIM_SOURCE:
            tmp = f"{shim_path}.tmp.{os.getpid()}"
            with open(tmp, "w", encoding="utf-8") as fh:
                fh.write(_SHIM_SOURCE)
            os.replace(tmp, shim_path)

        os.environ[RECEIPT_DIR_ENV] = receipt_dir
        os.environ[IMPORT_PATCHES_ENV] = "1" if import_patches else "0"
        os.environ["EXASERVE_DEPLOYMENT_ID"] = str(deployment_id)
        os.environ["EXASERVE_GENERATION"] = str(generation)
        os.environ["EXASERVE_VENDOR"] = str(vendor)
        for key, value in (versions or {}).items():
            os.environ[f"EXASERVE_VERSION_{key.upper()}"] = str(value)

        existing = os.environ.get("PYTHONPATH", "")
        if shim_dir not in existing.split(os.pathsep):
            os.environ["PYTHONPATH"] = (
                shim_dir + (os.pathsep + existing if existing else ""))
        return True
    except OSError:
        return False


def write_engine_receipt(*, patches_imported: bool) -> Optional[str]:
    """Called INSIDE the engine process by the shim. Never raises."""
    directory = os.environ.get(RECEIPT_DIR_ENV)
    if not directory:
        return None
    try:
        from .activator import _postcondition_sitecustomize
        from .profile import default_profile
        from .receipt import build_receipt

        profile = default_profile(os.environ.get("EXASERVE_VENDOR", "xpu"))
        required = profile.required_patch_ids("engine")
        results: dict[str, bool] = {}
        not_applicable: list[str] = []
        for patch_id in required:
            if not patches_imported:
                # The patch set was never delivered to this process. Claiming
                # it applied would be false; claiming it FAILED would be wrong
                # too, because nothing asked this process to carry it.
                not_applicable.append(patch_id)
                continue
            verdict = _postcondition_sitecustomize(patch_id)
            if verdict is None:
                not_applicable.append(patch_id)
            else:
                results[patch_id] = bool(verdict)

        versions = {}
        for key in ("ray", "vllm", "python"):
            value = os.environ.get(f"EXASERVE_VERSION_{key.upper()}")
            if value:
                versions[key] = value
        receipt = build_receipt(
            profile=profile, role="engine",
            deployment_id=os.environ.get("EXASERVE_DEPLOYMENT_ID", "unknown"),
            generation=int(os.environ.get("EXASERVE_GENERATION", "0") or 0),
            patch_results=results, attestation="self", versions=versions,
            not_applicable=tuple(not_applicable))
        payload = receipt.to_dict()
        payload["patches_delivered"] = bool(patches_imported)

        path = os.path.join(directory, f"engine_{os.getpid()}.json")
        tmp = f"{path}.tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, sort_keys=True)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
        return path
    except Exception:
        return None


def collect(receipt_dir: str, *, timeout_s: float = 0.0,
            poll_s: float = 0.25) -> list[dict]:
    """Replica-side: read receipts written by engine processes.

    ``timeout_s`` bounds a short wait for the first receipt, because the engine
    writes it during its own startup. Absence is not an error here — the caller
    falls back to owner attestation and records which evidence class was used.
    """
    deadline = time.monotonic() + max(0.0, timeout_s)
    while True:
        found: list[dict] = []
        for path in sorted(glob.glob(os.path.join(receipt_dir, "engine_*.json"))):
            try:
                with open(path, encoding="utf-8") as fh:
                    data = json.load(fh)
            except (OSError, ValueError):
                continue
            if isinstance(data, dict):
                found.append(data)
        if found or time.monotonic() >= deadline:
            return found
        time.sleep(poll_s)


def receipt_dir_for(deployment_id: str, generation: int) -> str:
    """Node-local, generation-scoped so a prior run's receipts cannot be read."""
    return os.path.join("/tmp", f"exaserve_engine_receipts_{deployment_id}_{generation}")


def prune(receipt_dirs: Iterable[str]) -> None:
    for directory in receipt_dirs:
        try:
            for path in glob.glob(os.path.join(directory, "engine_*.json")):
                os.unlink(path)
        except OSError:
            pass
