#!/bin/bash
#PBS -l select=512
#PBS -l walltime=01:00:00
#PBS -q prod
#PBS -l filesystems=home:flare
#PBS -A AuroraGPT
#PBS -N debug-sleep512
#PBS -l place=scatter
#PBS -o /home/wenyiw/aurora_rayserver/tmp/debug-sleep512.stdout
#PBS -e /home/wenyiw/aurora_rayserver/tmp/debug-sleep512.stderr
echo "NODE=$(hostname)"
echo "JOBID=$PBS_JOBID"
cp "$PBS_NODEFILE" "$HOME/.aurora_nodefile.$PBS_JOBID"
echo "NODEFILE=$HOME/.aurora_nodefile.$PBS_JOBID"
echo "NODES=$(sort -u "$PBS_NODEFILE" | wc -l)"
sleep 3500
