"""
NGINX backend implementation.

Generates an nginx.conf that load-balances across Ray Serve HTTP proxies,
then launches the nginx binary in foreground mode (daemon off).

NGINX is a pure L7 reverse proxy; like HAProxy it has no OpenAI awareness.
It is included as a second pure-LB baseline alongside HAProxy for comparison
against the LiteLLM (Python) and Pingora (multi-threaded Rust) baselines.

nginx must be installed and on PATH (see scripts/build_nginx.sh).
"""

import signal
import socket
import subprocess
import time
from collections import defaultdict
from pathlib import Path
from textwrap import dedent

from .base import BackendEndpoint, ProxyBackend


class NGINXProxy(ProxyBackend):
    """Manages an NGINX process as the request router."""

    def generate_config(
        self,
        backends: list[BackendEndpoint],
        output_dir: Path,
        **options,
    ) -> Path:
        """
        Write nginx.conf to output_dir. Returns the config path.

        Options (all optional):
            lb_method (str):       "least_conn" | "round_robin" | "random".
                                   Default: "least_conn".
            worker_processes (str|int): "auto" or an integer. Default: "auto".
            worker_connections (int):   Per-worker connection limit. Default: 50000.
            keepalive (int):       Upstream keepalive idle connections. Default: 256.
            keepalive_requests (int): Max requests per upstream conn. Default: 10000.
            proxy_read_timeout (int): seconds. Default: 330 (matches Ray Serve).
            proxy_send_timeout (int): seconds. Default: 330.
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        lb_method = options.get("lb_method", "least_conn")
        worker_processes = options.get("worker_processes", "auto")
        worker_connections = int(options.get("worker_connections", 50000))
        keepalive = int(options.get("keepalive", 256))
        keepalive_requests = int(options.get("keepalive_requests", 10000))
        proxy_read_timeout = int(options.get("proxy_read_timeout", 330))
        proxy_send_timeout = int(options.get("proxy_send_timeout", 330))

        # nginx places pid/log files relative to the build-time prefix unless we
        # override them. Force everything into output_dir so concurrent nginx
        # instances on the same host don't clobber each other.
        pid_file = output_dir / "nginx.pid"
        error_log = output_dir / "error.log"
        access_log = output_dir / "access.log"
        client_body_temp = output_dir / "client_body_temp"
        proxy_temp = output_dir / "proxy_temp"
        for d in (client_body_temp, proxy_temp):
            d.mkdir(parents=True, exist_ok=True)

        # Group endpoints by model_id so each model gets its own upstream.
        by_model: dict[str, list[BackendEndpoint]] = defaultdict(list)
        for ep in backends:
            by_model[ep.model_id].append(ep)

        lines: list[str] = [
            "# nginx.conf -- generated by exaserve",
            "daemon off;",
            f"pid {pid_file};",
            f"error_log {error_log} warn;",
            f"worker_processes {worker_processes};",
            f"worker_rlimit_nofile {max(65536, worker_connections * 2)};",
            "",
            "events {",
            f"    worker_connections {worker_connections};",
            "    use epoll;",
            "    multi_accept on;",
            "}",
            "",
            "http {",
            "    access_log off;",
            f"    client_body_temp_path {client_body_temp};",
            f"    proxy_temp_path {proxy_temp};",
            "    proxy_http_version 1.1;",
            "    proxy_set_header Connection \"\";",
            "    proxy_buffering off;",         # required for OpenAI streaming
            "    proxy_request_buffering off;",
            f"    proxy_read_timeout {proxy_read_timeout}s;",
            f"    proxy_send_timeout {proxy_send_timeout}s;",
            "    proxy_connect_timeout 5s;",
            "    client_max_body_size 100m;",
            "",
        ]

        # Emit one upstream block per model_id.
        for model_id, eps in by_model.items():
            up_name = _safe_name(model_id)
            lines.append(f"    upstream {up_name} {{")
            if lb_method == "least_conn":
                lines.append("        least_conn;")
            elif lb_method == "random":
                lines.append("        random;")
            # round_robin = default; no directive needed
            for ep in eps:
                lines.append(
                    f"        server {ep.host}:{ep.port} max_fails=3 fail_timeout=30s;"
                )
            lines.append(f"        keepalive {keepalive};")
            lines.append(f"        keepalive_requests {keepalive_requests};")
            lines.append("    }")
            lines.append("")

        # Single listener with per-model routing.
        lines.append("    server {")
        lines.append("        listen {PORT};")
        if len(by_model) == 1:
            up_name = _safe_name(next(iter(by_model)))
            lines.append("        location / {")
            lines.append(f"            proxy_pass http://{up_name};")
            lines.append("        }")
        else:
            for model_id, eps in by_model.items():
                up_name = _safe_name(model_id)
                path_prefix = _shared_path_prefix(eps)
                lines.append(f"        location {path_prefix}/ {{")
                lines.append(f"            proxy_pass http://{up_name};")
                lines.append("        }")
            lines.append("        location / { return 404 \"missing or unknown model route prefix\\n\"; }")
        # /nginx-status is a tiny status endpoint usable as a TCP/HTTP health probe.
        lines.append("        location = /nginx-status { stub_status; allow all; }")
        lines.append("    }")
        lines.append("}")

        config_text = "\n".join(lines) + "\n"
        config_path = output_dir / "nginx.conf"
        with open(config_path, "w") as f:
            f.write(config_text)

        total_servers = sum(len(eps) for eps in by_model.values())
        print(
            f"[NGINXProxy] Config written to {config_path} "
            f"({len(by_model)} model(s), {total_servers} upstream server(s), "
            f"lb={lb_method}, workers={worker_processes})"
        )
        return config_path

    def start(self, config_path: Path, host: str, port: int, **kwargs) -> tuple[subprocess.Popen, int]:
        """
        Launch nginx -c <config> in foreground (daemon off; in config).

        Resolves the {PORT} placeholder by rewriting the config in place.
        """
        text = config_path.read_text()
        text = text.replace("{PORT}", str(port))
        config_path.write_text(text)

        # nginx -p <prefix> -c <conf>. -p sets the working dir for relative
        # paths inside the config (we use absolute paths so this is just
        # cosmetic, but it prevents fall-back to the build-time prefix).
        prefix = str(config_path.parent) + "/"
        cmd = ["nginx", "-p", prefix, "-c", str(config_path)]
        print(f"[NGINXProxy] Starting: {' '.join(cmd)}", flush=True)
        proc = subprocess.Popen(cmd)
        print(f"[NGINXProxy] Process started (pid={proc.pid}, port={port})", flush=True)
        return proc, port

    def health_check(
        self,
        host: str,
        port: int,
        timeout: float = 30.0,
        process: subprocess.Popen | None = None,
    ) -> bool:
        check_host = "127.0.0.1" if host in ("0.0.0.0", "") else host
        deadline = time.monotonic() + timeout
        attempt = 0
        while time.monotonic() < deadline:
            if process is not None and process.poll() is not None:
                print(
                    f"[NGINXProxy] Process exited with code {process.returncode} "
                    f"before becoming healthy.",
                    flush=True,
                )
                return False
            attempt += 1
            try:
                with socket.create_connection((check_host, port), timeout=2):
                    print(
                        f"[NGINXProxy] Healthy after {attempt} attempt(s) "
                        f"(port {port})",
                        flush=True,
                    )
                    return True
            except OSError:
                pass
            time.sleep(1)
        print(f"[NGINXProxy] Health check timed out after {timeout}s", flush=True)
        return False

    def stop(self, process: subprocess.Popen) -> None:
        """SIGQUIT for graceful shutdown, then SIGKILL after 15s."""
        if process.poll() is not None:
            return
        print(f"[NGINXProxy] Stopping proxy (pid={process.pid})", flush=True)
        process.send_signal(signal.SIGQUIT)
        try:
            process.wait(timeout=15)
        except subprocess.TimeoutExpired:
            print("[NGINXProxy] SIGQUIT timed out, sending SIGKILL", flush=True)
            process.kill()
            process.wait()
        print("[NGINXProxy] Proxy stopped.", flush=True)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_name(model_id: str) -> str:
    """Convert a model_id to an nginx-safe identifier."""
    return "u_" + model_id.replace("/", "_").replace(".", "_").replace("-", "_")


def _shared_path_prefix(endpoints: list[BackendEndpoint]) -> str:
    prefixes = {ep.path_prefix for ep in endpoints}
    if len(prefixes) != 1:
        raise ValueError(f"Inconsistent path_prefix values in backend set: {sorted(prefixes)!r}")
    return prefixes.pop()
