"""
NGINX backend implementation.

Generates an nginx.conf that load-balances across Ray Serve HTTP proxies.
The composition root owns process launch.

NGINX is a pure L7 reverse proxy; like HAProxy it has no OpenAI awareness.
It is included as a second pure-LB baseline alongside HAProxy for comparison
against the LiteLLM (Python) and Pingora (multi-threaded Rust) baselines.

nginx must be installed and on PATH (see scripts/build_nginx.sh).
"""

from collections import defaultdict
from pathlib import Path

from .base import (
    BackendEndpoint,
    ProxyBackend,
    reject_unknown_options,
    strict_int,
    strict_text,
    validate_endpoint,
)


class NGINXProxy(ProxyBackend):
    """Render the NGINX artifact consumed by the composition root."""

    def generate_config(
        self,
        backends: list[BackendEndpoint],
        output_dir: Path,
        **options,
    ) -> Path:
        """
        Write nginx.conf to output_dir. Returns the config path.

        Options (all optional):
            lb_method (str):       "least_conn" | "round_robin" | "random".
                                   Default: "least_conn".
            worker_processes (str|int): "auto" or an integer. Default: "auto".
            worker_connections (int):   Per-worker connection limit. Default: 50000.
            keepalive (int):       Upstream keepalive idle connections. Default: 256.
            keepalive_requests (int): Max requests per upstream conn. Default: 10000.
            proxy_read_timeout (int): seconds. Default: 330 (matches Ray Serve).
            proxy_send_timeout (int): seconds. Default: 330.
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        reject_unknown_options(
            options,
            {
                "keepalive",
                "keepalive_requests",
                "lb_method",
                "listen_port",
                "proxy_read_timeout",
                "proxy_send_timeout",
                "status_allow_from",
                "worker_connections",
                "worker_processes",
            },
            "nginx",
        )

        lb_method = strict_text(
            options.get("lb_method", "least_conn"),
            "proxy.options.lb_method",
            choices={"least_conn", "round_robin", "ip_hash"},
        )
        worker_processes = options.get("worker_processes", "auto")
        if worker_processes != "auto":
            worker_processes = strict_int(
                worker_processes, "proxy.options.worker_processes", minimum=1, maximum=4096
            )
        worker_connections = strict_int(
            options.get("worker_connections", 50000),
            "proxy.options.worker_connections",
            minimum=1,
            maximum=10_000_000,
        )
        keepalive = strict_int(
            options.get("keepalive", 256), "proxy.options.keepalive", minimum=0, maximum=1_000_000
        )
        keepalive_requests = strict_int(
            options.get("keepalive_requests", 10000),
            "proxy.options.keepalive_requests",
            minimum=1,
            maximum=10_000_000,
        )
        proxy_read_timeout = strict_int(
            options.get("proxy_read_timeout", 330),
            "proxy.options.proxy_read_timeout",
            minimum=1,
            maximum=86400,
        )
        proxy_send_timeout = strict_int(
            options.get("proxy_send_timeout", 330),
            "proxy.options.proxy_send_timeout",
            minimum=1,
            maximum=86400,
        )

        # nginx places pid/log files relative to the build-time prefix unless we
        # override them. Force everything into output_dir so concurrent nginx
        # instances on the same host don't clobber each other.
        pid_file = output_dir / "nginx.pid"
        error_log = output_dir / "error.log"
        client_body_temp = output_dir / "client_body_temp"
        proxy_temp = output_dir / "proxy_temp"
        for d in (client_body_temp, proxy_temp):
            d.mkdir(parents=True, exist_ok=True)

        # Group endpoints by model_id so each model gets its own upstream.
        by_model: dict[str, list[BackendEndpoint]] = defaultdict(list)
        for ep in backends:
            validate_endpoint(ep, "nginx")
            by_model[ep.model_id].append(ep)
        if not by_model:
            raise ValueError("NGINX requires at least one backend endpoint")

        lines: list[str] = [
            "# nginx.conf -- generated by exaserve",
            "daemon off;",
            f"pid {pid_file};",
            f"error_log {error_log} warn;",
            f"worker_processes {worker_processes};",
            f"worker_rlimit_nofile {max(65536, worker_connections * 2)};",
            "",
            "events {",
            f"    worker_connections {worker_connections};",
            "    use epoll;",
            "    multi_accept on;",
            "}",
            "",
            "http {",
            "    access_log off;",
            f"    client_body_temp_path {client_body_temp};",
            f"    proxy_temp_path {proxy_temp};",
            "    proxy_http_version 1.1;",
            '    proxy_set_header Connection "";',
            "    proxy_buffering off;",  # required for OpenAI streaming
            "    proxy_request_buffering off;",
            f"    proxy_read_timeout {proxy_read_timeout}s;",
            f"    proxy_send_timeout {proxy_send_timeout}s;",
            "    proxy_connect_timeout 5s;",
            "    client_max_body_size 100m;",
            "",
        ]

        # Emit one upstream block per model_id.
        for model_id, eps in by_model.items():
            up_name = _safe_name(model_id)
            lines.append(f"    upstream {up_name} {{")
            if lb_method == "least_conn":
                lines.append("        least_conn;")
            elif lb_method == "random":
                lines.append("        random;")
            # round_robin = default; no directive needed
            for ep in eps:
                lines.append(f"        server {ep.host}:{ep.port} max_fails=3 fail_timeout=30s;")
            lines.append(f"        keepalive {keepalive};")
            lines.append(f"        keepalive_requests {keepalive_requests};")
            lines.append("    }")
            lines.append("")

        # Single listener with per-model routing.
        lines.append("    server {")
        listen_port = strict_int(
            options.get("listen_port", 4001), "proxy.options.listen_port", minimum=1, maximum=65535
        )
        lines.append(f"        listen {listen_port};")
        if len(by_model) == 1:
            up_name = _safe_name(next(iter(by_model)))
            lines.append("        location / {")
            lines.append(f"            proxy_pass http://{up_name};")
            lines.append("        }")
        else:
            for model_id, eps in by_model.items():
                up_name = _safe_name(model_id)
                path_prefix = _shared_path_prefix(eps)
                lines.append(f"        location {path_prefix}/ {{")
                lines.append(f"            proxy_pass http://{up_name};")
                lines.append("        }")
            lines.append(
                '        location / { return 404 "missing or unknown model route prefix\\n"; }'
            )
        # PR-010: /nginx-status exposes connection and request counters. It is
        # useful as a health probe, but `allow all` published it to anything
        # that could reach the proxy. Loopback by default; widening it is an
        # explicit, per-deployment opt-in that must name the allowed sources.
        status_allow = options.get("status_allow_from", ["127.0.0.1"])
        if isinstance(status_allow, str):
            status_allow = [status_allow]
        if not isinstance(status_allow, (list, tuple)) or not status_allow:
            raise ValueError(
                "proxy.options.status_allow_from must be a non-empty list of "
                "CIDRs/addresses (or the string 'all' to publish it)"
            )
        allow_rules = " ".join(
            "allow all;" if str(a).strip().lower() == "all" else f"allow {a};" for a in status_allow
        )
        lines.append(f"        location = /nginx-status {{ stub_status; {allow_rules} deny all; }}")
        lines.append("    }")
        lines.append("}")

        config_text = "\n".join(lines) + "\n"
        config_path = output_dir / "nginx.conf"
        from ..state.atomic import atomic_create_or_verify_text

        atomic_create_or_verify_text(config_path, config_text)

        total_servers = sum(len(eps) for eps in by_model.values())
        print(
            f"[NGINXProxy] Config written to {config_path} "
            f"({len(by_model)} model(s), {total_servers} upstream server(s), "
            f"lb={lb_method}, workers={worker_processes})"
        )
        return config_path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _safe_name(model_id: str) -> str:
    """Convert a model_id to an nginx-safe identifier."""
    return "u_" + model_id.replace("/", "_").replace(".", "_").replace("-", "_")


def _shared_path_prefix(endpoints: list[BackendEndpoint]) -> str:
    prefixes = {ep.path_prefix for ep in endpoints}
    if len(prefixes) != 1:
        raise ValueError(f"Inconsistent path_prefix values in backend set: {sorted(prefixes)!r}")
    return prefixes.pop()
